### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by danPwiz** [frontegg/frontegg-angular#418]
**Describe the bug**
This library can't be used with angular 16.

**To Reproduce**
1. Create a new angular 16 app
2. install this library with `npm i @frontegg/angular`
3. add FronteggAppModule to appModule
4. serve application
5. see error

**Expected behavior**
Expected to work with the latest versions of angular.

**Comment by MashaPav** [comment]
Hi there @danPwiz !

Our frontegg/angular SDK doesn't support yet Angular 16. Please email us at support@frontegg.com and we will add you to the notifications list for the release of a new SDK version that will support Angular 16. Otherwise, please monitor our [documentation guides](https://docs.frontegg.com/docs/angular-hosted-login-guide) that also mention the supported versions.

**Comment by yuvalotem1** [comment]
@danPwiz We added support for angular 16, now available on the latest
